Repository glowfic-constellation/glowfic, pull requests merged in 2018-05, with the labels that each got.

#801 Add gitlab dependency scanning
  .gitlab-ci.yml
Labels: 3. medium priority, 7. easy, dev

#803 Improve seeds
  db/seeds.rb
Labels: 3. medium priority, 9. hard, dev

#811 Upgrade to Ruby 2.5.1
  .travis.yml
  Gemfile
  Gemfile.lock
Labels: 2. high priority, 7. easy, dev
