Repository glowfic-constellation/glowfic, pull requests merged in 2018-07, with the labels that each got.

#838 Upgrade rubocop
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/post.rb
  lib/post_scraper.rb
Labels: 4. low priority, 8. medium, dev

#840 Change update_attributes to update
  app/concerns/owable.rb
  app/concerns/viewable.rb
  app/controllers/api/v1/board_sections_controller.rb
  app/controllers/api/v1/characters_controller.rb
  app/controllers/api/v1/posts_controller.rb
  app/controllers/boards_controller.rb
  app/controllers/icons_controller.rb
  app/controllers/index_sections_controller.rb
  app/controllers/indexes_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/templates_controller.rb
  app/controllers/users_controller.rb
  app/jobs/update_model_job.rb
  app/models/character.rb
  app/models/galleries_icon.rb
  app/models/post.rb
  app/models/reply.rb
  db/seeds.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/board_sections_controller_spec.rb
  spec/controllers/boards_controller_spec.rb
  spec/controllers/favorites_controller_spec.rb
  spec/controllers/icons_controller_spec.rb
  spec/controllers/indexes_controller_spec.rb
  spec/controllers/messages_controller_spec.rb
  spec/controllers/posts_controller_spec.rb
  spec/controllers/replies_controller_spec.rb
  spec/controllers/reports_controller_spec.rb
  spec/features/posts/new_spec.rb
  spec/features/posts/search_spec.rb
  spec/features/posts/show_spec.rb
  spec/features/posts/unread_spec.rb
  spec/jobs/notify_followers_of_new_post_job_spec.rb
  spec/models/board_spec.rb
  spec/models/character_spec.rb
  spec/models/character_tag_spec.rb
  spec/models/gallery_tag_spec.rb
  spec/models/post_spec.rb
  spec/models/reply_spec.rb
Labels: 4. low priority, 7. easy, dev

#839 Add sass linter config
  .sass-lint.yml
Labels: 3. medium priority, 8. medium, dev

#643 Consolidate starries
  app/assets/stylesheets/layouts/_dark_themes_selectors.scss
  app/assets/stylesheets/layouts/_defaults.scss
  app/assets/stylesheets/layouts/_starry_default_selectors.scss
  app/assets/stylesheets/layouts/_starry_default_variables.scss
  app/assets/stylesheets/layouts/starry.scss
  app/assets/stylesheets/layouts/starrydark.scss
  app/assets/stylesheets/layouts/starrylight.scss
Labels: 3. medium priority, 8. medium, dev

#851 gallery#add_new: Don't process directional keys as grid movement if text selected
  app/assets/javascripts/galleries/add_new.js
Labels: 3. medium priority, 7. easy, type: bug

#852 Ensure moderators can edit posts in boards they can't write in
  app/views/posts/_write.haml
  spec/factories.rb
  spec/features/posts/edit_spec.rb
Labels: 1. critical, 7. easy, type: bug
