Repository glowfic-constellation/glowfic, pull requests merged in 2018-10, with the labels that each got.

#887 Fix nil .fields error
  app/controllers/icons_controller.rb
Labels: type: bug

#889 Use bundle exec to handle gem conflicts
  bin-docker/rspec
Labels: u. ready to review

#885 Upgrade gems for Oct 03 2018
  Gemfile
  Gemfile.lock
  app/views/writable/_history.haml
  config/initializers/rack_timeout.rb
Labels: u. ready to review

#882 Upgrade rubocop to 0.59
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: u. ready to review

#890 Improve API docs
  Gemfile.lock
  app/controllers/api/v1/board_sections_controller.rb
  app/controllers/api/v1/boards_controller.rb
  app/controllers/api/v1/characters_controller.rb
  app/controllers/api/v1/galleries_controller.rb
  app/controllers/api/v1/icons_controller.rb
  app/controllers/api/v1/posts_controller.rb
  app/controllers/api/v1/replies_controller.rb
  app/controllers/api/v1/tags_controller.rb
  app/controllers/api/v1/users_controller.rb
  bin-docker/record_examples
Labels: u. ready to review

#880 Make posts_from_relation use keyword arguments
  app/controllers/application_controller.rb
  app/controllers/boards_controller.rb
  app/controllers/indexes_controller.rb
  app/controllers/posts_controller.rb
  app/views/boards/show.haml
  app/views/index_sections/_single.haml
  spec/controllers/application_controller_spec.rb
Labels: u. ready to review

#900 Add --rm flags to docker-compose run commands, to autoremove containers
  bin-docker/bundle
  bin-docker/psql
  bin-docker/rails
  bin-docker/rake
  bin-docker/record_examples
  bin-docker/rspec
Labels: 3. medium priority, dev
