Repository glowfic-constellation/glowfic, pull requests merged in 2018-03, with the labels that each got.

#738 Squish together some 'validates' statements
  app/models/user.rb
Labels: 7. easy, dev

#733 Use Rails.root.join
  app/controllers/application_controller.rb
  app/controllers/posts_controller.rb
  app/jobs/scrape_post_job.rb
  config/initializers/apipie.rb
  script/scraper_effulgence.rb
  script/scraper_incandescence.rb
  spec/controllers/posts_controller_spec.rb
  spec/jobs/scrape_post_job_spec.rb
  spec/lib/post_scraper_spec.rb
Labels: dev

#726 Dev/has dependent
  app/models/board.rb
  app/models/board_section.rb
  app/models/character.rb
  app/models/character_group.rb
  app/models/gallery.rb
  app/models/icon.rb
  app/models/post.rb
  spec/models/character_spec.rb
Labels: dev

#740 Replace .gsub with .tr
  app/controllers/posts_controller.rb
  lib/post_scraper.rb
Labels: 7. easy, dev

#742 Fix various basic lints
  app/controllers/application_controller.rb
  app/models/icon.rb
  app/models/report.rb
  app/presenters/post_presenter.rb
  spec/controllers/application_controller_spec.rb
  spec/jobs/application_job_spec.rb
  spec/models/post_spec.rb
Labels: 3. medium priority, 7. easy, dev

#741 Fix various layout lints
  app/controllers/characters_controller.rb
  app/controllers/galleries_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/tags_controller.rb
  app/helpers/writable_helper.rb
  app/models/galleries_icon.rb
  db/migrate/20171001035221_move_setting_to_tags.rb
  lib/memorylogic.rb
  spec/controllers/api/v1/posts_controller_spec.rb
  spec/features/boards/show_spec.rb
  spec/features/messages/show_spec.rb
  spec/features/seed_spec.rb
Labels: dev

#737 Remove unused variable assignments
  app/concerns/taggable.rb
  app/controllers/api/v1/templates_controller.rb
  app/models/character.rb
  app/models/gallery.rb
  app/models/gallery_tag.rb
  lib/post_scraper.rb
  script/scraper_effulgence.rb
  spec/controllers/api/v1/boards_controller_spec.rb
  spec/controllers/api/v1/characters_controller_spec.rb
  spec/controllers/api/v1/posts_controller_spec.rb
  spec/controllers/api/v1/templates_controller_spec.rb
  spec/controllers/api/v1/users_controller_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/boards_controller_spec.rb
  spec/controllers/characters_controller_spec.rb
  spec/controllers/galleries_controller_spec.rb
  spec/controllers/posts_controller_spec.rb
  spec/controllers/replies_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/features/favorites/index_spec.rb
  spec/features/messages/show_spec.rb
  spec/features/posts/search_spec.rb
  spec/features/templates/new_spec.rb
  spec/jobs/notify_followers_of_new_post_job_spec.rb
  spec/jobs/scrape_post_job_spec.rb
  spec/lib/post_scraper_spec.rb
  spec/models/board_spec.rb
  spec/models/character_tag_spec.rb
  spec/models/post_author_spec.rb
Labels: 4. low priority, 7. easy, dev

#739 Fix various style lints
  Gemfile
  app/concerns/taggable.rb
  app/controllers/application_controller.rb
  app/controllers/board_sections_controller.rb
  app/controllers/characters_controller.rb
  app/controllers/galleries_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/replies_controller.rb
  app/controllers/reports_controller.rb
  app/controllers/users_controller.rb
  app/controllers/writable_controller.rb
  app/helpers/tag_helper.rb
  app/models/character.rb
  app/models/post.rb
  app/models/reply.rb
  app/models/tag.rb
  config/application.rb
  lib/memorylogic.rb
  spec/controllers/posts_controller_spec.rb
  spec/support/spec_feature_helper.rb
Labels: dev

#750 Upgrade gems for 2018-03-04
  Gemfile.lock
  app/models/board.rb
  script/scraper_effulgence.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/models/board_spec.rb
  spec/models/message_spec.rb
  spec/models/reply_spec.rb
  spec/models/user_spec.rb
Labels: 1. critical, 8. medium, dev

#748 Upgrade to Ruby 2.5.0
  .rubocop.yml
  .travis.yml
  Gemfile
  Gemfile.lock
Labels: 2. high priority, 8. medium, dev

#688 Add reply_order migration
  db/migrate/20180109003825_add_reply_order_to_replies.rb
  db/structure.sql
Labels: dev

#725 Add inverse_of
  app/models/board.rb
  app/models/character.rb
  app/models/character_tag.rb
  app/models/gallery_tag.rb
  app/models/message.rb
  app/models/post.rb
  app/models/post_tag.rb
  app/models/user.rb
Labels: dev

#770 Feature spec galleries#index
  spec/features/galleries/index_spec.rb
  spec/support/spec_feature_helper.rb
Labels: 3. medium priority, 7. easy, dev

#772 Add character#show feature specs
  app/controllers/aliases_controller.rb
  app/controllers/characters_controller.rb
  app/controllers/galleries_controller.rb
  app/controllers/icons_controller.rb
  app/controllers/templates_controller.rb
  app/views/aliases/new.haml
  app/views/characters/edit.haml
  app/views/characters/replace.haml
  app/views/characters/show.haml
  app/views/galleries/_single.haml
  app/views/galleries/edit.haml
  app/views/galleries/show.haml
  app/views/icons/edit.haml
  app/views/icons/replace.haml
  app/views/icons/show.haml
  app/views/templates/edit.haml
  app/views/templates/new.haml
  app/views/templates/show.haml
  spec/controllers/aliases_controller_spec.rb
  spec/controllers/characters_controller_spec.rb
  spec/controllers/galleries_controller_spec.rb
  spec/controllers/icons_controller_spec.rb
  spec/controllers/templates_controller_spec.rb
  spec/features/characters/show_spec.rb
  spec/features/galleries/index_spec.rb
Labels: 2. high priority, 8. medium, dev

#777 Implement moieties better
  app/assets/stylesheets/layout.scss
  app/models/user.rb
  app/views/users/show.haml
  spec/models/user_spec.rb
Labels: 2. high priority, 7. easy, type: enhancement

#776 Add an 'Edit Post' button to posts#stats
  app/views/posts/stats.haml
Labels: 2. high priority, 7. easy, type: enhancement

#778 Fix icons background color on starrydark
  app/assets/stylesheets/layouts/starrydark.scss
Labels: 2. high priority, 7. easy, type: bug

#779 Upgrade rubocop to 0.54
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: 3. medium priority, 8. medium, dev

#780 Avoid attempting to include coauthor information on solo threads
  app/jobs/notify_followers_of_new_post_job.rb
  spec/jobs/notify_followers_of_new_post_job_spec.rb
Labels: 3. medium priority, 7. easy, type: bug

#782 Fix contribute link for pull requests
  app/views/contribute/index.haml
Labels: 2. high priority, 7. easy, type: bug

#734 Use bang methods for create/update/destroy
  app/controllers/aliases_controller.rb
  app/controllers/api/v1/characters_controller.rb
  app/controllers/board_sections_controller.rb
  app/controllers/boards_controller.rb
  app/controllers/characters_controller.rb
  app/controllers/favorites_controller.rb
  app/controllers/galleries_controller.rb
  app/controllers/icons_controller.rb
  app/controllers/index_posts_controller.rb
  app/controllers/index_sections_controller.rb
  app/controllers/indexes_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/password_resets_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/replies_controller.rb
  app/controllers/tags_controller.rb
  app/controllers/templates_controller.rb
  app/jobs/generate_flat_post_job.rb
  app/models/reply.rb
  script/character_scraper.rb
  spec/controllers/aliases_controller_spec.rb
  spec/controllers/api/v1/boards_controller_spec.rb
  spec/controllers/api/v1/characters_controller_spec.rb
  spec/controllers/api/v1/tags_controller_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/board_sections_controller_spec.rb
  spec/controllers/boards_controller_spec.rb
  spec/controllers/characters_controller_spec.rb
  spec/controllers/favorites_controller_spec.rb
  spec/controllers/galleries_controller_spec.rb
  spec/controllers/icons_controller_spec.rb
  spec/controllers/index_posts_controller_spec.rb
  spec/controllers/index_sections_controller_spec.rb
  spec/controllers/indexes_controller_spec.rb
  spec/controllers/posts_controller_spec.rb
  spec/controllers/replies_controller_spec.rb
  spec/controllers/reports_controller_spec.rb
  spec/controllers/tags_controller_spec.rb
  spec/controllers/templates_controller_spec.rb
  spec/features/posts/new_spec.rb
  spec/features/posts/search_spec.rb
  spec/features/posts/show_spec.rb
  spec/features/posts/unread_spec.rb
  spec/jobs/generate_flat_post_job_spec.rb
  spec/jobs/notify_followers_of_new_post_job_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/board_section_spec.rb
  spec/models/board_spec.rb
  spec/models/character_spec.rb
  spec/models/character_tag_spec.rb
  spec/models/characters_gallery_spec.rb
  spec/models/flat_post_spec.rb
  spec/models/gallery_tag_spec.rb
  spec/models/icon_spec.rb
  spec/models/index_section_spec.rb
  spec/models/post_spec.rb
  spec/models/reply_spec.rb
  spec/models/template_spec.rb
Labels: 2. high priority, 8. medium, dev
