Repository glowfic-constellation/glowfic, pull requests merged in 2018-06, with the labels that each got.

#825 Override layout-th styling in post-content tables
  app/assets/stylesheets/replies.scss
Labels: 2. high priority, 7. easy, type: bug

#827 Add bold font to reply ths
  app/assets/stylesheets/replies.scss
Labels: 3. medium priority, 7. easy, type: enhancement

#812 Fix Ruby and Rails versions in README
  README.md
Labels: 4. low priority, 7. easy, dev

#781 Automatically lock imports to authors
  lib/post_scraper.rb
  spec/jobs/scrape_post_job_spec.rb
  spec/lib/post_scraper_spec.rb
Labels: 3. medium priority, 7. easy, type: enhancement
