Repository glowfic-constellation/glowfic, pull requests merged in 2019-07, with the labels that each got.

#1101 Add list of validation tools to README
  README.md
Labels: u. ready to review

#1102 Catch and handle InvalidAuthenticityToken errors
  app/assets/stylesheets/layout.scss
  app/controllers/application_controller.rb
  app/controllers/replies_controller.rb
  app/controllers/writable_controller.rb
  app/models/post.rb
  app/views/sessions/new.haml
  spec/controllers/posts_controller_spec.rb
Labels: u. ready to review

#1103 Unify error flashes with others
  app/views/layouts/application.haml
Labels: 4. low priority, 7. easy

#1070 Order posts by last updated in tags#show posts view
  app/controllers/tags_controller.rb
Labels: u. ready to review

#1052 Consistently use begin/rescue/else syntax on create/update/destroy
  .rubocop.yml
  app/controllers/aliases_controller.rb
  app/controllers/blocks_controller.rb
  app/controllers/board_sections_controller.rb
  app/controllers/boards_controller.rb
  app/controllers/characters_controller.rb
  app/controllers/favorites_controller.rb
  app/controllers/galleries_controller.rb
  app/controllers/icons_controller.rb
  app/controllers/index_posts_controller.rb
  app/controllers/index_sections_controller.rb
  app/controllers/indexes_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/news_controller.rb
  app/controllers/password_resets_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/replies_controller.rb
  app/controllers/tags_controller.rb
  app/controllers/templates_controller.rb
  app/controllers/users_controller.rb
  spec/controllers/characters_controller_spec.rb
  spec/controllers/galleries_controller_spec.rb
  spec/controllers/posts_controller_spec.rb
  spec/controllers/templates_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/features/templates/new_spec.rb
Labels: u. ready to review

#1067 Clean up prefixed linear-gradient functions
  app/assets/stylesheets/global.scss
Labels: u. ready to review

#1056 Merge _galleryless.haml into _single.haml
  app/controllers/galleries_controller.rb
  app/views/characters/show.haml
  app/views/galleries/_single.haml
  app/views/galleries/show.haml
  app/views/icons/show.haml
Labels: u. ready to review

#1105 Clean up _galleryless.haml
  app/views/galleries/_galleryless.haml
Labels: u. ready to review

#856 Add more open graph data
  app/controllers/board_sections_controller.rb
  app/controllers/boards_controller.rb
  app/controllers/characters_controller.rb
  app/controllers/galleries_controller.rb
  app/controllers/icons_controller.rb
  app/controllers/news_controller.rb
  app/controllers/tags_controller.rb
  app/controllers/templates_controller.rb
  app/controllers/users_controller.rb
  app/views/layouts/application.haml
  spec/controllers/board_sections_controller_spec.rb
  spec/controllers/boards_controller_spec.rb
  spec/controllers/characters_controller_spec.rb
  spec/controllers/galleries_controller_spec.rb
  spec/controllers/icons_controller_spec.rb
  spec/controllers/news_controller_spec.rb
  spec/controllers/tags_controller_spec.rb
  spec/controllers/templates_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: 3. medium priority, 7. easy, type: enhancement

#1107 Update Code Climate config file to new 2.0 format
  .codeclimate.yml
Labels: u. ready to review

#1109 Consolidate html_safe on sanitize_written_content
  app/helpers/application_helper.rb
  app/views/boards/show.haml
  app/views/characters/_icon_view.haml
  app/views/characters/_list_section.haml
  app/views/characters/show.haml
  app/views/index_sections/_single.haml
  app/views/indexes/show.haml
  app/views/messages/_message.haml
  app/views/news/_news.haml
  app/views/posts/_generate_flat.haml
  app/views/posts/flat.haml
  app/views/replies/_single.haml
  app/views/replies/search.haml
  app/views/tags/_info.haml
  app/views/user_mailer/new_message.html.haml
  app/views/user_mailer/post_has_new_reply.html.haml
  app/views/users/output.haml
Labels: u. ready to review

#1112 Strip spaces from character facecasts
  app/models/character.rb
  spec/models/character_spec.rb
Labels: u. ready to review

#1111 Simplify the visible_to scope a little
  app/models/post.rb
Labels: u. ready to review

#1114 Allow links in icon credits
  app/helpers/application_helper.rb
  app/helpers/writable_helper.rb
  app/views/board_sections/show.haml
  app/views/boards/show.haml
  app/views/icons/show.haml
  app/views/messages/_message.haml
  app/views/posts/_list_item.haml
  app/views/posts/flat.haml
  app/views/posts/preview.haml
  app/views/posts/show.haml
  app/views/posts/stats.haml
  app/views/replies/preview.haml
  app/views/reports/_daily.haml
  app/views/writable/_history.haml
  spec/helpers/application_helper_spec.rb
Labels: u. ready to review

#1110 Upgrade rubocop version from 0.68 to 0.73
  .codeclimate.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: u. ready to review

#1116 Temporarily make galleries#single use multiple tbodys
  app/views/characters/show.haml
  app/views/galleries/_single.haml
Labels: type: bug

#1118 Test users#index and users#search with feature specs (also fix some HTML errors)
  app/views/users/index.haml
  app/views/users/search.haml
  spec/features/users/index_spec.rb
  spec/features/users/search_spec.rb
Labels: dev

#1122 Use dependent: :nullify and :destroy correctly
  app/concerns/owable.rb
  app/models/board.rb
  app/models/character.rb
  app/models/gallery.rb
  app/models/icon.rb
  app/models/index.rb
  app/models/index_section.rb
  app/models/post.rb
  app/models/setting.rb
  app/models/tag.rb
  spec/models/icon_spec.rb
Labels: u. ready to review
