Repository glowfic-constellation/glowfic, pull requests merged in 2019-12, with the labels that each got.

#1238 Use a virtual volume for Postgres Docker data
  docker-compose.yml
Labels: 3. medium priority, 7. easy, dev, u. ready to review

#1229 Add .dockerignore file
  .dockerignore
Labels: 3. medium priority, 7. easy, dev, u. ready to review

#1237 Improve .travis.yml (use Bionic, updated Bundler, and Postgres 10)
  .travis.yml
Labels: 3. medium priority, 7. easy, dev, u. ready to review

#1236 Upgrade deps as of 2019-11-16
  Gemfile
  Gemfile.lock
Labels: 2. high priority, 8. medium, dependencies

#1235 Upgrade bundler to 2.0.2
  Dockerfile
  Gemfile.lock
Labels: 4. low priority, 7. easy, dependencies, dev, u. ready to review

#1163 Save memory on characters list view
  app/helpers/character_helper.rb
  app/models/character.rb
  app/views/characters/_list_section.haml
  spec/helpers/character_helper_spec.rb
Labels: u. ready to review

#1148 Upgrade pg to 1.1.4
  Gemfile
  Gemfile.lock
Labels: 2. high priority, 7. easy, dev, u. ready to review

#1265 Use multiple jobs in Dockerfile bundle install
  Dockerfile
Labels: 4. low priority, 7. easy, dev

#1270 Add ESLint to our Dockerfile, fix some code around it
  .codeclimate.yml
  .eslintignore
  .eslintrc.yml
  Dockerfile
  app/assets/javascripts/accept_tos.js
  app/assets/javascripts/blocks.js
  app/assets/javascripts/boards/show.js
  app/assets/javascripts/characters/editor.js
  app/assets/javascripts/galleries/add_existing.js
  app/assets/javascripts/galleries/edit.js
  app/assets/javascripts/galleries/editor.js
  app/assets/javascripts/galleries/update_existing.js
  app/assets/javascripts/galleries/uploader.js
  app/assets/javascripts/global.js
  app/assets/javascripts/posts/index_post_new.js
  app/assets/javascripts/posts/search.js
  app/assets/javascripts/posts/show.js
  app/assets/javascripts/posts/unread.js
  app/assets/javascripts/users/output.js
Labels: 3. medium priority, 8. medium, dev

#1146 Test JS with selenium-webdriver and capybara
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  app/assets/javascripts/galleries/expander_old.js
  app/assets/stylesheets/global.scss
  app/views/galleries/_single.haml
  docker-compose.yml
  spec/features/characters/show_spec.rb
  spec/spec_helper.rb
Labels: 3. medium priority, 8. medium, dev, u. ready to review

#1199 Feature spec sessions#new and sessions#destroy
  spec/features/sessions/destroy_spec.rb
  spec/features/sessions/new_spec.rb
Labels: 3. medium priority, 7. easy, dev, u. ready to review

#1274 Use sanitize_sql_array instead of connection.quote
  app/controllers/users_controller.rb
  app/services/daily_report.rb
Labels: dev

#1278 Disable NewRelic in dev mode without a license key
  config/newrelic.yml
Labels: 3. medium priority, 7. easy, dev

#1279 Improve timeout behavior (Rack::Timeout and PG statement_timeout)
  Gemfile
  Gemfile.lock
  Procfile
  config/database.yml
  config/puma.rb
Labels: 2. high priority, 8. medium, dependencies, type: bug

#1277 Use Docker for PostgreSQL & Redis dependencies by default
  README.md
  config/database.yml
  docker-compose.yml
Labels: 4. low priority, dev

#1284 Improve job exception handling, slightly
  app/jobs/application_job.rb
  spec/jobs/generate_flat_post_job_spec.rb
Labels: 2. high priority, 7. easy, type: bug

#1283 Expire flat post locks after 30 minutes
  app/jobs/generate_flat_post_job.rb
  spec/jobs/generate_flat_post_job_spec.rb
Labels: 3. medium priority, 7. easy, type: bug

#1286 Order API docs and reset IDs between examples
  doc/apipie_examples.json
  spec/spec_helper.rb
Labels: dev

#1288 Add user moiety & created_at to API
  app/controllers/api/v1/users_controller.rb
  app/presenters/user_presenter.rb
  doc/apipie_examples.json
  spec/controllers/api/v1/users_controller_spec.rb
Labels: 3. medium priority, 7. easy, type: new feature

#1287 Add section order to posts in the /boards/:id/posts API
  app/presenters/post_presenter.rb
  doc/apipie_examples.json
Labels: 3. medium priority, 7. easy, type: bug
