Repository glowfic-constellation/glowfic, pull requests merged in 2019-10, with the labels that each got.

#1174 Seed uploaded image URLs with a random string in the Javascript 2: The Seedening
  app/assets/javascripts/application.js
  app/assets/javascripts/galleries/uploader.js
  app/controllers/galleries_controller.rb
  app/controllers/uploading_controller.rb
  app/models/icon.rb
  spec/controllers/galleries_controller_spec.rb
  spec/models/icon_spec.rb
Labels: u. ready to review

#1137 Update gems for 2019-08-01
  Dockerfile
  Gemfile.lock
  app/models/post.rb
  app/models/reply.rb
  config/newrelic.yml
  config/puma.rb
  docker-compose.yml
Labels: u. ready to review

#1175 Use safe_join rather than join + html_safe
  app/views/boards/_list_item.haml
  app/views/characters/_list_section.haml
  app/views/characters/show.haml
  app/views/posts/_write.haml
  app/views/posts/stats.haml
  app/views/tags/_info.haml
Labels: u. ready to review

#1176 Fix characters quick search colspan
  app/views/characters/index.haml
Labels: u. ready to review

#1197 Fix duplicate id errors on login page
  app/views/layouts/application.haml
  app/views/sessions/new.haml
Labels: 4. low priority, 7. easy, dev, type: bug

#1198 Reorder Dockerfile commands for cache reuse
  Dockerfile
Labels: 4. low priority, 7. easy, dev

#1167 Use visible_to scope for post previous/next
  app/controllers/writable_controller.rb
  spec/controllers/posts_controller_spec.rb
Labels: u. ready to review

#1201 Manually order in board ordering test
  spec/controllers/boards_controller_spec.rb
Labels: 3. medium priority, 7. easy, dev

#1200 Use Node 10 in Docker
  Dockerfile
Labels: 3. medium priority, 7. easy, dev

#1202 Update Bundler to 1.17.3
  Dockerfile
Labels: 4. low priority, 7. easy, dev
