Repository glowfic-constellation/glowfic, pull requests merged in 2019-11, with the labels that each got.

#1210 Add Constellation Discord to about pages
  app/views/about/contact.haml
  app/views/sessions/index.haml
  config/application.rb
Labels: 3. medium priority, 7. easy, type: bug

#996 Clean up rubocop file
  .rubocop.yml
  app/controllers/blocks_controller.rb
  app/controllers/characters_controller.rb
  app/helpers/application_helper.rb
  app/helpers/writable_helper.rb
  app/models/post.rb
  app/models/user.rb
  app/presenters/post_presenter.rb
  app/services/post_scraper.rb
  spec/controllers/characters_controller_spec.rb
  spec/controllers/posts_controller_spec.rb
  spec/features/galleries/index_spec.rb
  spec/features/replies/new_spec.rb
  spec/lib/presentable_spec.rb
  spec/models/daily_report_spec.rb
  spec/services/post_scraper_spec.rb
  spec/support/spec_feature_helper.rb
Labels: discussion encouraged

#1228 Upgrade dev redis to 4.0 to match prod
  docker-compose.yml
Labels: 3. medium priority, 7. easy, dev, u. ready to review

#1231 Add Resque worker to docker-compose.yml
  config/environments/development.rb
  docker-compose.yml
Labels: 3. medium priority, 7. easy, dev, u. ready to review

#1234 Combine apt-get update and apt-get install in Dockerfile
  Dockerfile
Labels: 3. medium priority, 7. easy, dev, u. ready to review
