Repository glowfic-constellation/glowfic, pull requests merged in 2020-02, with the labels that each got.

#1333 Fix icon galleries view for memory
  app/views/galleries/_icon_item.haml
  app/views/galleries/_icon_view.haml
  app/views/galleries/_list_item.haml
  app/views/galleries/_list_section.haml
Labels: 2. high priority, 7. easy

#1328 Add replies.post_id to reply_order index
  db/migrate/20200201234346_add_post_reply_order_index_to_replies.rb
  db/migrate/20200201234427_remove_reply_index_from_replies.rb
  db/schema.rb
Labels: 2. high priority, 7. easy, dev

#1334 Skip 0-change in memory log, humanize negatives
  lib/memorylogic.rb
Labels: 3. medium priority, 7. easy, dev

#1335 Add barnes gem for Heroku additional metrics
  Gemfile
  Gemfile.lock
  config/puma.rb
Labels: 3. medium priority, dev

#1336 Revert "Enable barnes only in production"
  Gemfile
  config/puma.rb
Labels: type: bug

#1338 Allow retiring characters
  app/controllers/characters_controller.rb
  app/controllers/writable_controller.rb
  app/models/template.rb
  app/views/characters/_editor.haml
  db/migrate/20200209021236_add_retired_to_characters.rb
  db/schema.rb
  spec/controllers/writable_controller_spec.rb
  spec/features/characters/show_spec.rb
  spec/models/template_spec.rb
Labels: has-migration

#1344 Update chromium to new buster-provided version
  Dockerfile
Labels: 3. medium priority, dev
