Repository glowfic-constellation/glowfic, pull requests merged in 2020-05, with the labels that each got.

#1383 Upgrade to Ruby 2.6.6
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
Labels: dependencies

#1408 Upgrade json to 2.3.0
  Gemfile
  Gemfile.lock
Labels: 2. high priority, dependencies

#1120 Make methods with several arguments use keyword arguments
  app/concerns/taggable.rb
  app/concerns/viewable.rb
  app/controllers/api/api_controller.rb
  app/controllers/api/v1/characters_controller.rb
  app/controllers/api/v1/replies_controller.rb
  app/controllers/api/v1/templates_controller.rb
  app/controllers/characters_controller.rb
  app/controllers/galleries_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/replies_controller.rb
  app/controllers/reports_controller.rb
  app/controllers/tags_controller.rb
  app/controllers/writable_controller.rb
  app/helpers/application_helper.rb
  app/services/report.rb
  app/views/posts/_generate_flat.haml
  app/views/posts/flat.haml
  spec/controllers/boards_controller_spec.rb
  spec/controllers/posts_controller_spec.rb
  spec/controllers/replies_controller_spec.rb
  spec/controllers/reports_controller_spec.rb
  spec/controllers/writable_controller_spec.rb
  spec/models/daily_report_spec.rb
  spec/models/post_spec.rb
Labels: u. ready to review
