Repository glowfic-constellation/glowfic, pull requests merged in 2023-09, with the labels that each got.

#1329 Reload URL hash after accepting TOS if applicable
  app/assets/javascripts/accept_tos.js
  app/assets/javascripts/global.js
  app/views/about/_accept_tos.haml
Labels: type: bug, 7. easy, 3. medium priority, u. ready to review

#1525 Upgrade to sprockets 4
  .eslintignore
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  config/initializers/assets.rb
Labels: u. ready to review, dependencies

#1363 Timezoneify timestamps for logged out users
  app/assets/javascripts/application_deferred.js
  app/assets/javascripts/datetimes.js
  app/helpers/application_helper.rb
  app/views/layouts/application.haml
Labels: type: enhancement, 7. easy, 3. medium priority, u. ready to review

#1298 Add minio to replicate S3 bucket functionality locally
  .github/workflows/rspec.yml
  config/initializers/aws.rb
  docker-compose.yml
  spec/controllers/api/v1/icons_controller_spec.rb
  spec/controllers/galleries_controller_spec.rb
  spec/jobs/delete_icon_from_s3_job_spec.rb
  spec/support/s3_bucket_helper.rb
Labels: dev, 7. easy, 4. low priority

#1041 Record editor mode on replies and posts
  app/concerns/writable.rb
  app/controllers/posts_controller.rb
  app/controllers/writable_controller.rb
  app/helpers/writable_helper.rb
  app/services/reply_scraper.rb
  app/views/posts/_generate_flat.haml
  app/views/posts/_write.haml
  app/views/posts/flat.haml
  app/views/replies/_single.haml
  app/views/replies/_write.haml
  app/views/replies/search.haml
  app/views/user_mailer/post_has_new_reply.html.haml
  app/views/users/output.haml
  db/migrate/20190505014536_add_editor_mode_to_replies.rb
  db/schema.rb
  db/seeds/post.rb
  db/seeds/reply.rb
  script/add_editor_mode.rb
  spec/controllers/replies/create_spec.rb
  spec/factories.rb
  spec/features/posts/edit_spec.rb
  spec/features/posts/flat_spec.rb
  spec/features/posts/new_spec.rb
  spec/helpers/writable_helper_spec.rb
Labels: has-migration
