Repository glowfic-constellation/glowfic, pull requests merged in 2024-12, with the labels that each got.

#2292 Add option to retire templates
  app/controllers/templates_controller.rb
  app/controllers/writable_controller.rb
  app/models/character.rb
  app/models/template.rb
  app/views/characters/_icon_view.haml
  app/views/characters/_list_section.haml
  app/views/characters/index.haml
  app/views/templates/_editor.haml
  app/views/templates/show.haml
  db/migrate/20241130175900_add_retired_to_templates.rb
  db/schema.rb
  spec/controllers/characters_controller_spec.rb
  spec/controllers/templates_controller_spec.rb
  spec/controllers/writable_controller_spec.rb
  spec/models/character_spec.rb
Labels: type: new feature, has-migration

#2298 Add UI for thread splitting
  app/assets/images/icons/cut.png
  app/assets/images/icons/cut_closed.png
  app/assets/images/icons/cut_red.png
  app/assets/stylesheets/global.scss
  app/controllers/admin/posts_controller.rb
  app/controllers/posts_controller.rb
  app/jobs/split_post_job.rb
  app/views/admin/admin/index.haml
  app/views/admin/posts/split.haml
  app/views/posts/_split.haml
  app/views/posts/preview_split.haml
  app/views/posts/show.haml
  app/views/posts/split.haml
  app/views/replies/_single.haml
  config/routes.rb
  spec/controllers/admin/posts_controller_spec.rb
  spec/controllers/posts/split_spec.rb
  spec/jobs/split_post_job_spec.rb
  spec/requests/admin_spec.rb
Labels: design/ui, type: new feature

#2311 Fix psql command
  bin-docker/psql
Labels: type: bug

#2319 Add "Check All" checkboxes to all pages
  app/assets/javascripts/global.js
  app/assets/stylesheets/layout.scss
  app/controllers/notifications_controller.rb
  app/views/messages/index.haml
  app/views/notifications/_notification.haml
  app/views/notifications/index.haml
  app/views/posts/_list.haml
  app/views/posts/_list_item.haml
  app/views/posts/hidden.haml
  spec/system/messages/show_spec.rb
  spec/system/notifications/index_spec.rb
  spec/system/posts/unread_spec.rb
Labels: type: enhancement, design/ui, u. ready to review

#2320 updates to code in readme
  README.md
Labels: 4. low priority, u. ready to review

#2315 Add author content warnings
  app/assets/javascripts/users/edit.js
  app/assets/stylesheets/layout.scss
  app/controllers/tags_controller.rb
  app/controllers/users_controller.rb
  app/controllers/writable_controller.rb
  app/models/tag.rb
  app/models/user.rb
  app/models/user_tag.rb
  app/views/posts/show.haml
  app/views/tags/_users.haml
  app/views/tags/show.haml
  app/views/users/_list.haml
  app/views/users/edit.haml
  app/views/users/index.haml
  app/views/users/show.haml
  db/migrate/20241209191600_add_user_tags.rb
  db/schema.rb
  db/seeds/tag.rb
  spec/controllers/tags_controller_spec.rb
  spec/models/tag_spec.rb
  spec/system/posts/show_spec.rb
  spec/system/users/edit_spec.rb
  spec/system/users/show_spec.rb
Labels: design/ui, type: new feature, u. ready to review, has-migration, ruby

#2328 Replace inline HTML with Haml
  app/views/layouts/mailer.html.haml
  app/views/posts/_generate_flat.haml
  app/views/posts/flat.haml
  app/views/posts/show.haml
  app/views/replies/_single.haml
Labels: u. ready to review

#2329 Condense author warning specs' scenarios
  spec/system/posts/show_spec.rb
  spec/system/users/show_spec.rb
Labels: u. ready to review

#2327 Add user bookmarks
  .rubocop.yml
  app/assets/images/icons/bookmark.png
  app/assets/images/icons/bookmark_delete.png
  app/assets/images/icons/bookmark_pencil.png
  app/assets/javascripts/bookmarks/rename.js
  app/assets/javascripts/posts/edit_notes.js
  app/assets/javascripts/posts/search.js
  app/assets/stylesheets/global.scss
  app/controllers/api/v1/bookmarks_controller.rb
  app/controllers/api/v1/posts_controller.rb
  app/controllers/api/v1/replies_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/bookmarks_controller.rb
  app/controllers/users_controller.rb
  app/models/bookmark.rb
  app/models/post.rb
  app/models/reply.rb
  app/models/user.rb
  app/views/bookmarks/search.haml
  app/views/posts/show.haml
  app/views/replies/_single.haml
  app/views/search/_breadcrumbs.haml
  app/views/users/_infobox.haml
  app/views/users/edit.haml
  config/routes.rb
  db/migrate/20241222000400_add_user_bookmarks.rb
  db/schema.rb
  spec/controllers/api/v1/bookmarks_controller_spec.rb
  spec/controllers/api/v1/posts_controller_spec.rb
  spec/controllers/api/v1/replies_controller_spec.rb
  spec/controllers/api/v1/users_controller_spec.rb
  spec/controllers/bookmarks/create_spec.rb
  spec/controllers/bookmarks/destroy_spec.rb
  spec/controllers/bookmarks/search_spec.rb
  spec/factories.rb
  spec/system/bookmarks/search_spec.rb
  spec/system/posts/show_spec.rb
  spec/system/users/show_spec.rb
Labels: design/ui, type: new feature, u. ready to review, has-migration, ruby

#2338 Use inline-block display with sub-600px screen width
  app/assets/stylesheets/layout.scss
Labels: design/ui, u. ready to review

#2350 Turn profile horizontal scroll to auto rather than scroll
  app/assets/stylesheets/layout.scss
Labels: type: bug, design/ui, u. ready to review

#2351 Add specs for the split post UI thing
  app/views/posts/_split.haml
  spec/system/posts/show_spec.rb
Labels: type: bug, type: enhancement, u. ready to review

#2344 Add settings to hide reply buttons
  app/assets/images/icons/link_delete.png
  app/assets/images/icons/link_go.png
  app/controllers/users_controller.rb
  app/views/posts/show.haml
  app/views/replies/_single.haml
  app/views/users/edit.haml
  db/migrate/20241224202900_add_default_hide_reply_buttons.rb
  db/schema.rb
  spec/system/posts/show_spec.rb
  spec/system/users/edit_spec.rb
Labels: type: enhancement, design/ui, has-migration
